### PR TITLE
changes landsat

### PR DESCRIPTION
**Pull request by carioca-au**
Changes on landsat logic... now avoiding USGS API

### CODE REVIEW

**Review by NikitaGandhi — APPROVED** [review]
I trust your python code :)

**Comment by NikitaGandhi** [comment]
Provide working dev DAG link for reference

**Review by carioca-au — COMMENTED** [review]
added zfill to the logic

**Comment by carioca-au** [comment]
> Provide working dev DAG link for reference

@NikitaGandhi in this case I can add some links, however, they won't be just DAG links because the logic isn't with the DAG, I split that in a different Python script.

These are the DAGS in DEV AIrflow
https://airflow.dev.digitalearth.africa/tree?dag_id=landsat_scenes_identifying - identifying DEV DAG
https://airflow.dev.digitalearth.africa/tree?dag_id=landsat_scenes_processing - processing DEV DAG
https://airflow.dev.digitalearth.africa/tree?dag_id=landsat_scenes_indexing - indexing DEV DAG
https://github.com/digitalearthafrica/deafrica-airflow/tree/develop-af/dags/landsat_scenes_sync - CODE

These are the logic Python scripts :
https://github.com/digitalearthafrica/deafrica-airflow/blob/develop-af/dags/utils/landsat_scenes_identifying_logic.py - identifying DEV

https://github.com/digitalearthafrica/deafrica-airflow/blob/develop-af/dags/utils/landsat_scenes_sync_process_logic.py - processing DEV

Anybody, please feel free to contact me if you need any explanation.

Thank you

**Review by fivejjs — APPROVED** [review]

**Pull request merged**
